AWSTemplateFormatVersion: '2010-09-09'
Description: 'Ethereum Fraud Detection Pipeline - Complete Infrastructure'

Parameters:
  ProjectName:
    Type: String
    Default: 'ethereum-fraud-detection'
    Description: 'Project name for resource naming'
  
  EtherscanApiKey:
    Type: String
    NoEcho: true
    Description: 'Etherscan API Key'
    Default: '92PHT62WJFSRXFPMJ84JD51GK2NHCI9KJ3'
  
  EthereumAddress:
    Type: String
    Description: 'Ethereum address to monitor'
    Default: '0x742d35Cc6634C0532925a3b844Bc454e4438f44e'

Resources:
  # IAM Role for Glue
  GlueEtherscanRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'GlueEtherscanRole'
      Description: 'Role for Glue job to ingest Etherscan data to S3'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # Glue Job for Data Ingestion
  EtherscanIngestionJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: 'etherscan-data-ingestion'
      Description: 'Fetch Ethereum transactions from Etherscan API and store in S3'
      Role: !GetAtt GlueEtherscanRole.Arn
      Command:
        Name: 'pythonshell'
        PythonVersion: '3.9'
        ScriptLocation: 's3://de-27-team11/scripts/etherscan_to_s3_glue.py'
      DefaultArguments:
        '--ETHERSCAN_API_KEY': !Ref EtherscanApiKey
        '--ETH_ADDRESS': !Ref EthereumAddress
        '--RAW_BUCKET_NAME': 'de-27-team11'
        '--job-language': 'python'
      MaxRetries: 1
      Timeout: 30
      GlueVersion: '3.0'
      MaxCapacity: 0.0625
      Tags:
        Project: !Ref ProjectName

  # Glue Database for Catalog
  EthereumDatabase:
    Type: 'AWS::Glue::Database'
    Properties:
      CatalogId: !Ref 'AWS::AccountId'
      DatabaseInput:
        Name: 'ethereum_fraud_detection'
        Description: 'Database for Ethereum transaction data'

  # Glue Crawler for Raw Data
  RawDataCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Name: 'ethereum-raw-data-crawler'
      Role: !GetAtt GlueEtherscanRole.Arn
      DatabaseName: !Ref EthereumDatabase
      Description: 'Crawler for raw Ethereum transaction data'
      Targets:
        S3Targets:
          - Path: 's3://de-27-team11/raw/ethereum/txlist/'
      SchemaChangePolicy:
        UpdateBehavior: 'UPDATE_IN_DATABASE'
        DeleteBehavior: 'LOG'
      Tags:
        Project: !Ref ProjectName

Outputs:
  GlueRoleArn:
    Description: 'ARN of the Glue IAM Role'
    Value: !GetAtt GlueEtherscanRole.Arn
    Export:
      Name: !Sub '${ProjectName}-glue-role-arn'
  
  IngestionJobName:
    Description: 'Name of the Etherscan ingestion Glue job'
    Value: !Ref EtherscanIngestionJob
    Export:
      Name: !Sub '${ProjectName}-ingestion-job-name'
  
  DatabaseName:
    Description: 'Name of the Glue database'
    Value: !Ref EthereumDatabase
    Export:
      Name: !Sub '${ProjectName}-database-name'
  
  CrawlerName:
    Description: 'Name of the raw data crawler'
    Value: !Ref RawDataCrawler
    Export:
      Name: !Sub '${ProjectName}-crawler-name'